### ISSUE TITLE
Defecto 1 - navegación por chrome no funciona

### ISSUE THREAD

**Issue by samantatorrez** [samantatorrez/giannerWeb#3]
Por firefox funciona, pero no por Chrome.
Pregunta Adicional: ¿Al poner una url por ejemplo: http://localhost/giannerWeb/contacto no debería direccionar a la página con el correspondiente tpl ?

**Comment by FerMagGonzalez** [comment]
Ya lo probe por lo dos y anda.
Lo de la pregunta adicional, lo estoy revisando pero no logro que ande. El miercoles pregunto en la clase practica.
